######STAT701 Homework 1 - Landon Budge, John Costa, Brandon Muirhead#################

##########################
####### PROBLEM 1 ########
##########################

### Part (a): exploring, cleaning, and summarizing the data

getwd()
dir=c("~/Wharton/STAT/Data")
setwd(dir)
getwd()
radio=read.csv("Survey_results_final.csv",header=T, stringsAsFactors=F,as.is=T, na.strings="")

### Basic exploratory analysis of the data
class(radio)
str(radio)
fix(radio)  # There are many columns in this table we simply don't care about

### Create a subset of original data containing only the relevant variables
colnames(radio)
radio1=radio[,c(28:33)]
names(radio1)=c("age", "education", "gender", "income", "sirius", "wharton")
summary(as.factor(radio1$age))  # Unusual entries require some cleaning up

### Cleaning up the "age" variable
radio1$age[radio1$age == "27`"] <- 27
radio1$age[radio1$age == "Eighteen (18)"] <- 18
radio1$age[radio1$age == "female"] <- NA
radio1$age=as.numeric(radio1$age)
radio2=radio1[(radio1$age >15) & (radio1$age < 100), ]

### Remove entries where either Sirus = NA or Wharton = NA
radio2=radio2[!is.na(radio2$sirius),]
radio2=radio2[!(radio2$sirius==""),]
radio2=radio2[!is.na(radio2$wharton),]
radio2=radio2[!(radio2$wharton==""),]
summary(as.factor(radio2$sirius))
summary(as.factor(radio2$wharton))
dim(radio2)
paste("The complete data has", dim(radio2)[1], "cases")

### Ensure variables are properly designated as nominal or continuous
radio2$wharton=as.factor(radio2$wharton)
radio2$sirius=as.factor(radio2$sirius)
radio2$gender=as.factor(radio2$gender)
radio2$income=as.factor(radio2$income)
radio2$education=as.factor(radio2$education)
radio2$age=as.numeric(radio2$age)

### Summarizing the data
summary(radio2$age)
summary(radio2$education)
summary(radio2$income)
summary(radio2$gender)
summary(radio2$sirius)
summary(radio2$wharton)

### Visualizing the data

hist(radio2$age, breaks=20, freq=F, col="red", 
     main="Histogram of Respondent's Age", 
     xlab="Age")

library(ggplot2)

qplot(factor(education), data=radio2, geom="bar", fill=factor(education))
qplot(factor(income), data=radio2, geom="bar", fill=factor(income))
qplot(factor(gender), data=radio2, geom="bar", fill=factor(gender))
qplot(factor(sirius), data=radio2, geom="bar", fill=factor(sirius))
qplot(factor(wharton), data=radio2, geom="bar", fill=factor(wharton))

### Part (b): See writeup for discussion on whether the data represents a random sample of the MTURK population

### Part (c): Is gender a statistical factor?

radio2=radio2[!is.na(radio2$gender),]
radio2=radio2[!(radio2$gender==""),]
summary(radio2$gender)

y=sum(radio2$gender=="Male")
n=nrow(radio2)
phat=y/n
se=sqrt(phat*(1-phat)/n)
z=(phat-0)/se
p.value=(1-pnorm(z))
round(1-pnorm(4), 6)  # The p-value indicates that H0: p=0.5 should be rejected. Therefore, we conclude that
# the proportion of males is significantly greater than the proportion of females

### Confidence interval for P(wharton | gender) compared with P(wharton)

prop.test(table(radio2$gender,radio2$wharton))  # CI = (0.0037, 0.0416)

x=sum(radio2$wharton=="Yes")
phat=x/n
se=sqrt(phat*(1-phat)/n)
ci=c(phat-1.96*se, phat+1.96*se)  # CI = (0.0309, 0.0492) which does not differ much from the CI above where
# we accounted for gender differences


###########################
####### PROBLEM 2  ########
###########################

###### 2.a

x <- seq(0, 1, length.out = 40)
z <- rnorm(n = 40, mean = 0, sd = 2)    #creates the errors with sd = 2 and mean = 0
y <- 1 + 1.2 * x + z

df <- data.frame(x, y)    #puts the data into a data frame

linear <- lm(y~x, data = df)
lm_coef <- round(coef(linear), 3) # extract coefficients 
plot(x = x, y = y, pch=16, xlab="X Values", 
      ylab="Y Values")  #plot the points

abline(linear, col="red", lwd=4)         # plot best fit line 

mtext(bquote(y == .(lm_coef[2])*x + .(lm_coef[1])), 
      adj = 1, padj = 0) # display equation in top right

summary(linear)   #True B1 should be 1.2 also used to find RMSE

ci <- confint(linear)
ci[2,]            #calculates the CI for B1



###### 2.b Estimating the slope

#(b)i)

b1 <- numeric(0)  #holds list of beta 1s generated by each sample
ci <- data.frame(matrix(nrow = 100, ncol = 2))  #to hold a list of confidence intervals generated
pvals <- numeric(0)     #to hold a list of p-values for each sample generated
x <- seq(0, 1, length.out = 40)
for (i in 1:100) {
      e <- 2 * rnorm(length(x))
      y <- 1 + 1.2*x + e
      l2 <- lm(y~x)
      conf <- confint(l2)
      ttest <- t.test(x,y)
      b1[i] <- l2$coe[2]
      ci[i,] <- conf[2,] 
      pvals[i] <- ttest[3]
}

hist(b1, breaks=30, col="cornflowerblue", main = "Distribution of Sample B1s", xlab = "Estimated B1", 
     ylim = c(0,15), xlim = c(-2, 4))
summary(b1)

#(b)ii)

cover <- ci[1] < 1.2 & ci[2] > 1.2  #true/false does CI contain true mean of 1.2?

ci_not_true <- (100 - sum(cover))/100     #% of CIs that do not contain true mean
ci_not_true

num_not_true <- (100-sum(cover))    #number of times CI does not contain true mean of 1.2
num_not_true

num_true <- sum(cover)
num_true

coverFactor <- as.factor(cover)
barplot(table(cover), main = "Confidence Interval Contains True Mean", ylim = c(0,108))
      text(0.7, 10, num_not_true)
      text(1.9, 105, num_true)

#(b)iii)

reject <- sum(pvals[1:100] < 0.05) #counts the number of times the null hypothesis was rejected
noreject <- 100 - reject
M <- matrix(c(noreject, reject), nrow = 1, ncol = 2)
colnames(M) <- c("Not Rejected", "Rejected")

barplot(M, main = "Was the null hypothesis rejected?", ylim = c(0,108), col = "darkblue")
      text(0.7, 15, noreject)
      text(1.9, 93, reject)


##########################
####### PROBLEM 3 ########
##########################



#Load and prepare the data
setwd("~/Wharton/STAT/Data")
rawdata <- read.csv("MLPayData.csv",header=T,as.is=T)
names(rawdata)
names(rawdata)[1]="team" # rename "Team.name.2014" as "team"

#Add average win percentage (avgwin) and cumulative pay (payroll)
rawdata$payroll <- rowSums(rawdata[,(2:18)])/1000  #convert to billions
rawdata$avgwin <- rowMeans(rawdata[,(36:52)])
names(rawdata)
datapay <- rawdata[c(1:18,36:54)]    #exclude the number of wins fields for simplicity
datapay <- datapay[c(1:18,35:19,36,37)]   #reorder columns
names(datapay)


#i) Summarize the data


#Calculate the two LS lines
myfit0 <- lm(avgwin~payroll, data=datapay)    #avgwin is y and payroll is x
myfit1 <- lm(payroll~avgwin, data=datapay)    #reverse of the above

#For the reverse regression, need to express in like terms (e.g., create second y)
summary(myfit1)
beta0 <- myfit1$coefficients[1]
beta1 <- myfit1$coefficients[2]
avgwin2 <- (datapay$payroll-beta0)/beta1   

#Plot the first LS line
par(mgp=c(1.8,.5,0), mar=c(3,3,2,1)) 
plot(datapay$payroll, datapay$avgwin, pch=16, 
     xlab="Cumulative Payroll 1998-2014", ylab="Average Win Percentage 1998-2014",
     main="MLB Overall Win Percentage vs. Payroll")
abline(lm(avgwin~payroll, data=datapay), col="red", lwd=4) 

#Overlay the second LS line  
lines(datapay$payroll, avgwin2, col="green", lwd=4)

#Add legend
legend("bottomright", legend=c("y=winpercent", "y=payroll"),
       lty=c(1,1), lwd=c(2,2), col=c("red","green"))

#Add label to Oakland, NY and Boston only

Labels1 <- datapay[c(4,19,20),c(1,36:37)]
text(Labels1$payroll, Labels1$avgwin, Labels1$team, cex= 0.7, pos=1)


#ii)Winning percentage by year for each team, 1998-2014


#create vector for years
years <- c(1998:2014)

#subset only the data required for the chart 
graph <- datapay[c(1,19:35)]

#use a loop to graph each team's winning percentage over time on the same chart
for(i in 1:30){
  if(i==1){
    plot(x=years,y=graph[1,-1],type="l",lwd=2,col=i,ylim=c(0.2,0.8),
         main="Win Percentages 1998-2014",xlab="Year",ylab="Win Percentage")
  }
  if(i!=1){
    lines(x=years,y=graph[i,-1],lwd=2,col=i)
  }
}


#Let's do the same thing for payroll over time and see if it looks similar
graph2 <- datapay[c(1:18)]

for(i in 1:30){
  if(i==1){
    plot(x=years,y=graph2[1,-1],type="l",lwd=2,col=i,ylim=c(0,250),
         main="Annual Payroll 1998-2014",xlab="Year",ylab="Payroll ($million)")
  }
  if(i!=1){
    lines(x=years,y=graph2[i,-1],lwd=2,col=i)
  }
}


#iii) Examine relationship between payroll and win percentage in select years


#Prepare data for 2001 analysis
names(datapay)
iii2001 <- datapay[c(1,5,22)]
names(iii2001)
summary(iii2001)
mainlabels <- datapay[c(4,19,20),] #create a vector including only Oakland, Yankees, and BoSox (for labeling)

#Plot data for 2001 analysis
plot(X2001.pct ~ p2001, data=iii2001, ylab="2001 Winning Percentage", xlab="2001 Payroll", 
     main="2001 MLB Season", pch=16)

#label Boston, Oakland and Yankees
text(mainlabels$p2001, mainlabels$X2001.pct, mainlabels$team, cex= 0.7, pos=2, offset=-1)

#label the team with the best record that year
max2001 <- which.max(iii2001$X2001.pct)
maxlabel2001 <- iii2001[max01,]
text(maxlabel2001$p2001, maxlabel2001$X2001.pct, maxlabel2001$team, cex= 0.7, pos=2)

#Calculate least squares regression line
fit1 <- lm(X2001.pct ~ p2001, data=iii2001)
abline(fit1)

fit1_coef <- round(coef(fit1), 3) # extract coefficients 
mtext(bquote(y == .(fit1_coef[2])*x + .(fit1_coef[1])), 
      adj=1, padj=0) # display equation in top right

fit1_summary <- summary(fit1)
fit1_summary
R2_1 <- round(fit1_summary$r.squared,2)
mtext(bquote(R2 == .(R2_1)), adj=0, padj=0) #display R2 in top left


#Prepare data for 2006 analysis
names(datapay)
iii2006 <- datapay[c(1,10,27)]
names(iii2006)
summary(iii2006)

#Plot data for 2006 analysis
plot(X2006.pct ~ p2006, data=iii2006, ylab="2006 Winning Percentage", xlab="2006 Payroll", 
     main="2006 MLB Season", pch=16)

#label Boston, Oakland and Yankees
text(mainlabels$p2006, mainlabels$X2006.pct, mainlabels$team, cex= 0.7, pos=2, offset=-1)

#label the team with the best record that year
max06 <- which.max(iii2006$X2006.pct)
maxlabel2006 <- iii2006[max06,]
text(maxlabel2006$p2006, maxlabel2006$X2006.pct, maxlabel2006$team, cex= 0.7, pos=2)

#Calculate least squares regression line
fit2 <- lm(X2006.pct ~ p2006, data=iii2006)
abline(fit2)

fit2_coef <- round(coef(fit2), 3) # extract coefficients 
mtext(bquote(y == .(fit2_coef[2])*x + .(fit2_coef[1])), 
      adj=1, padj=0) # display equation in top right

fit2_summary <- summary(fit2)
fit2_summary
R2_2 <- round(fit2_summary$r.squared,2)
mtext(bquote(R2 == .(R2_2)), adj=0, padj=0) #display R2 in top left


#Prepare data for 2011 analysis
names(datapay)
iii2011 <- datapay[c(1,15,32)]
names(iii2011)
summary(iii2011)

#Plot data for 2011 analysis
plot(X2011.pct ~ p2011, data=iii2011, ylab="2011 Winning Percentage", xlab="2011 Payroll", 
     main="2011 MLB Season", pch=16)

#label Boston, Oakland and Yankees
text(mainlabels$p2011, mainlabels$X2011.pct, mainlabels$team, cex= 0.7, pos=2, offset=-1)

#label the team with the best record that year
max11 <- which.max(iii2011$X2011.pct)
maxlabel2011 <- iii2011[max11,]
text(maxlabel2011$p2011, maxlabel2011$X2011.pct, maxlabel2011$team, cex= 0.7, pos=1)

#Calculate least squares regression line
fit3 <- lm(X2011.pct ~ p2011, data=iii2011)
abline(fit3)

fit3_coef <- round(coef(fit3), 3) # extract coefficients 
mtext(bquote(y == .(fit3_coef[2])*x + .(fit3_coef[1])), 
      adj=1, padj=0) # display equation in top right

fit3_summary <- summary(fit3)
fit3_summary
R2_3 <- round(fit3_summary$r.squared,2)
mtext(bquote(R2 == .(R2_3)), adj=0, padj=0) #display R2 in top left


#iv) Questions about Boston and Oakland


#Boston Red Sox

BoSox <- datapay[4,c(1,36:37)] #create subset with only Boston
names(BoSox)
BoSox_p <- BoSox[2] #save payroll data
BoSox_w <- BoSox[3] #save win data

### 95% CI for a future winning percentage given total payroll of $2.1B

CIpred <-predict(myfit0, BoSox_p, interval="prediction", se.fit=TRUE)
CIpred

paste("Given Boston's total payroll of",round(BoSox_p,2), "billion, win percentage is expected to fall between"
      ,round(CIpred$fit[2],2),"and",round(CIpred$fit[3],2),"with 95% confidence."
      ,"Their average win rate of",round(BoSox_w,2),"falls within this range."
      ,"This suggests that they perform reasonably well given their total payroll.")

#Oakland A's

OakA <- datapay[20,c(1,36:37)] #create subset with only Oakland data
names(OakA)
OakA_p <- OakA[2]
OakA_w <- OakA[3]

### 95% CI for a total payroll given average winning percentage of 54%

CIpred2 <-predict(myfit1, OakA_w, interval="prediction", se.fit=TRUE)
CIpred2

paste("Given Oakland's win percentage of",round(OakA_w,2), "payroll in $B is expected to fall between"
      ,round(CIpred2$fit[2],2),"and",round(CIpred2$fit[3],2),"with 95% confidence."
      ,"Their total payroll of",round(OakA_p,2),"falls below this range."
      ,"This suggests that they should have had to spend at least"
      ,round(1000*(CIpred2$fit[2]-OakA_p),0),"million more dollars to achieve"
      ,"their actual winning percentage.")

paste("In fact, it would not be surprising for a team with Oakland's"
      ,"winning percentage to spend as much as",round(CIpred2$fit[3]-OakA_p,2)
      ,"billion more than Oakland did!","That being said, our best estimate"
      ,"of what they 'should have' spent is",round(CIpred2$fit[1],2),"billion.")